### ISSUE TITLE
PVP Flag

### ISSUE THREAD

**Issue by RyanClarke2** [Muqsit/WorldGuard#10]
Amazing plugin but the pvp flag is broken,i can set the pvp flag in a region true or flase np but when i do nothing happens.People can still pvp even when its set to false.

**Comment by Muqsit** [comment]
Issue produced. Didn't mean to close it.
This one is because the constant Human::NETWORK_ID doesn't exist (I thought it'd be an alternative to the "instanceof" check, and would be an optimization itself). My bad.
