### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by SourSmirnoff** [Muqsit/WorldGuard#13]
16.06 01:58:46 [Server] Server thread/CRITICAL ErrorException: "Undefined variable: regions" (EXCEPTION) in "/WorldGuard_v1.phar/src/WorldGuard/WorldGuard" at line 103

not sure here, need some help

**Comment by Muqsit** [comment]
This happens if the plugin cannot find the regions.yml file. I'll get it fixed soon
