### ISSUE TITLE
More flags idk lol[This is the basic population, it'll get worse again yet:p, on my machine, of course:P]

### ISSUE THREAD

**Issue by akaSnapy** [Muqsit/WorldGuard#16]
1-> When you enter on a selected area a custom title will show up.
2-> Disable Entities Dropping in a selected region(you won't be able to drop items on a region)
3-> Disable mob spawning in a region
4-> Disable Eating/Healing on selected regions
5-> Run a command when someone joined the area

**Comment by Muqsit** [comment]
#1
