### ISSUE TITLE
Just a console full of errors (:

### ISSUE THREAD

**Issue by SourSmirnoff** [Muqsit/WorldGuard#19]
29.07 23:52:10 [Server] Server thread/CRITICAL ErrorException: "Undefined index: N��6��[g6��" (EXCEPTION) in "WorldGuard_v1.phar/src/WorldGuard/WorldGuard" at line 261
29.07 23:52:10 [Server] INFO N��6��[g6�� on WorldGuard\EventListener

**Comment by Muqsit** [comment]
Do not modify the source

**Comment by SourSmirnoff** [comment]
Bro i didnt modify it? i literally just compiled the phar and threw it on the server

**Comment by Muqsit** [comment]
How do you compile it into phar?

**Comment by SourSmirnoff** [comment]
Most the time dev tools but if im lazy i just use pmt.mcpe.fun

In this case i used pmt
