### ISSUE TITLE
Disable-Flight

### ISSUE THREAD

**Issue by iDirtniverse** [Muqsit/WorldGuard#2]
Hello @Muqsit ,
I really find your plugin interesting, for me, there's thing I'd like to suggest is that flags with disabling flights. This case will be helpful of PvP arenas, thank you ;)

**Comment by Muqsit** [comment]
Do you mean setting creative mode players to survival mode?

**Comment by akaSnapy** [comment]
@Muqsit he wants a flag wich when u entered the areazone fly will be disabled.

**Comment by iDirtniverse** [comment]
Yes @Muqsit, when you enter a region that have flag disable-flight enabled they will stop flying,
as in this case I have a VIP rank which player can fly with /fly from EssentialsPE

it'll be really nice to add this flag :P

**Comment by akaSnapy** [comment]
@Muqsit @iDirtniverse The most easy thing what muq can do is to make that flat, and the flag "fly" firstly will check if /fly is enabled `https://github.com/LegendOfMCPE/EssentialsPE/blob/master/src/EssentialsPE/Commands/Fly.php`

**Comment by Muqsit** [comment]
Use "fly-mode" flag.
![xz](https://cloud.githubusercontent.com/assets/15074389/24009768/059af0f4-0a87-11e7-8a16-6c1b9ced6974.PNG)

If you want players to not fly, you can disable the command "/fly" in the region and also set the "fly-mode" flag to 2.
/region flag set <region> fly-mode 2
