### ISSUE TITLE
Giant bug

### ISSUE THREAD

**Issue by NikeboyHU** [Muqsit/WorldGuard#27]
11.10 18:03:53 [Server] Server thread/CRITICAL "Could not pass event 'pocketmine\event\player\PlayerMoveEvent' to 'WorldGuard v1': Return value of WorldGuard\Region::getEffects() must be of the type array, null returned on WorldGuard\EventListener
11.10 18:03:53 [Server] Server thread/CRITICAL TypeError: "Return value of WorldGuard\Region::getEffects() must be of the type array, null returned" (EXCEPTION) in "/WorldGuard_v1.phar/src/WorldGuard/Region" at line 240
11.10 18:03:53 [Server] Server thread/DEBUG #0 /WorldGuard_v1.phar/src/WorldGuard/WorldGuard(210): WorldGuard\WorldGuard->onRegionChange(pocketmine\Player Player(4), string , string teszt)
11.10 18:03:53 [Server] Server thread/DEBUG #1 /WorldGuard_v1.phar/src/WorldGuard/EventListener(143): WorldGuard\WorldGuard->updateRegion(pocketmine\Player Player(4))
11.10 18:03:53 [Server] Server thread/DEBUG #2 /src/pocketmine/plugin/MethodEventExecutor(45): WorldGuard\EventListener->onMove(pocketmine\event\player\PlayerMoveEvent object)
11.10 18:03:53 [Server] Server thread/DEBUG #3 /src/pocketmine/plugin/RegisteredListener(96): pocketmine\plugin\MethodEventExecutor->execute(WorldGuard\EventListener object, pocketmine\event\player\PlayerMoveEvent object)
11.10 18:03:53 [Server] Server thread/DEBUG #4 /src/pocketmine/plugin/PluginManager(718): pocketmine\plugin\RegisteredListener->callEvent(pocketmine\event\player\PlayerMoveEvent object)
11.10 18:03:53 [Server] Server thread/DEBUG #5 /src/pocketmine/Player(1815): pocketmine\plugin\PluginManager->callEvent(pocketmine\event\player\PlayerMoveEvent object)
11.10 18:03:53 [Server] Server thread/DEBUG #6 /src/pocketmine/Player(2023): pocketmine\Player->processMovement(integer 1)
11.10 18:03:53 [Server] Server thread/DEBUG #7 /src/pocketmine/level/Level(788): pocketmine\Player->onUpdate(integer 4125)
11.10 18:03:53 [Server] Server thread/DEBUG #8 /src/pocketmine/Server(2632): pocketmine\level\Level->doTick(integer 4125)
11.10 18:03:53 [Server] Server thread/DEBUG #9 /src/pocketmine/Server(2828): pocketmine\Server->checkTickUpdates(integer 4125, double 1507737833.6949)
11.10 18:03:53 [Server] Server thread/DEBUG #10 /src/pocketmine/Server(2548): pocketmine\Server->tick(boolean)
11.10 18:03:53 [Server] Server thread/DEBUG #11 /src/pocketmine/Server(2426): pocketmine\Server->tickProcessor(boolean)
11.10 18:03:53 [Server] Server thread/DEBUG #12 /src/pocketmine/Server(1997): pocketmine\Server->start(boolean)
11.10 18:03:53 [Server] Server thread/DEBUG #13 /src/pocketmine/PocketMine(492): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///GenisysPro_1.1dev-tomi.phar/, string /, string /plugins/)
11.10 18:03:53 [Server] Server thread/DEBUG #14 (1): require_once(string phar:///GenisysPro_1.1dev-tomi.phar/src/pocketmine/PocketMine.php)
11.10 18:04:27 [Server] Server thread/INFO cInformi? >> A szerveren más szervert hirdetni szigorúan Tilos!
11.10 18:04:52 [Server] Server thread/CRITICAL "Could not pass event 'pocketmine\event\player\PlayerMoveEvent' to 'WorldGuard v1': Return value of WorldGuard\Region::getEffects() must be of the type array, null returned on WorldGuard\EventListener
11.10 18:04:52 [Server] Server thread/CRITICAL TypeError: "Return value of WorldGuard\Region::getEffects() must be of the type array, null returned" (EXCEPTION) in "/WorldGuard_v1.phar/src/WorldGuard/Region" at line 240
11.10 18:04:52 [Server] Server thread/DEBUG #0 /WorldGuard_v1.phar/src/WorldGuard/WorldGuard(210): WorldGuard\WorldGuard->onRegionChange(pocketmine\Player Player(4), string , string teszt)
11.10 18:04:52 [Server] Server thread/DEBUG #1 /WorldGuard_v1.phar/src/WorldGuard/EventListener(143): WorldGuard\WorldGuard->updateRegion(pocketmine\Player Player(4))
11.10 18:04:52 [Server] Server thread/DEBUG #2 /src/pocketmine/plugin/MethodEventExecutor(45): WorldGuard\EventListener->onMove(pocketmine\event\player\PlayerMoveEvent object)
11.10 18:04:52 [Server] Server thread/DEBUG #3 /src/pocketmine/plugin/RegisteredListener(96): pocketmine\plugin\MethodEventExecutor->execute(WorldGuard\EventListener object, pocketmine\event\player\PlayerMoveEvent object)
11.10 18:04:52 [Server] Server thread/DEBUG #4 /src/pocketmine/plugin/PluginManager(718): pocketmine\plugin\RegisteredListener->callEvent(pocketmine\event\player\PlayerMoveEvent object)
11.10 18:04:52 [Server] Server thread/DEBUG #5 /src/pocketmine/Player(1815): pocketmine\plugin\PluginManager->callEvent(pocketmine\event\player\PlayerMoveEvent object)
11.10 18:04:52 [Server] Server thread/DEBUG #6 /src/pocketmine/Player(2023): pocketmine\Player->processMovement(integer 1)
11.10 18:04:52 [Server] Server thread/DEBUG #7 /src/pocketmine/level/Level(788): pocketmine\Player->onUpdate(integer 5294)
11.10 18:04:52 [Server] Server thread/DEBUG #8 /src/pocketmine/Server(2632): pocketmine\level\Level->doTick(integer 5294)
11.10 18:04:52 [Server] Server thread/DEBUG #9 /src/pocketmine/Server(2828): pocketmine\Server->checkTickUpdates(integer 5294, double 1507737892.1449)
11.10 18:04:52 [Server] Server thread/DEBUG #10 /src/pocketmine/Server(2548): pocketmine\Server->tick(boolean)
11.10 18:04:52 [Server] Server thread/DEBUG #11 /src/pocketmine/Server(2426): pocketmine\Server->tickProcessor(boolean)
11.10 18:04:52 [Server] Server thread/DEBUG #12 /src/pocketmine/Server(1997): pocketmine\Server->start(boolean)
11.10 18:04:52 [Server] Server thread/DEBUG #13 /src/pocketmine/PocketMine(492): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string phar:///GenisysPro_1.1dev-tomi.phar/, string /, string /plugins/)
11.10 18:04:52 [Server] Server thread/DEBUG #14 (1): require_once(string phar:///GenisysPro_1.1dev-tomi.phar/src/pocketmine/PocketMine.php)

**Comment by Muqsit** [comment]
"GenisysPro"
