### ISSUE TITLE
Fly flag like your server?

### ISSUE THREAD

**Issue by NycuRO** [Muqsit/WorldGuard#3]
You can add "fly-flag" like your server?

And if exit from area, get fly disabled? ( like your server ) ?

And if player get "fly-disabled" get and off  "fall damage" ?

And you can add flags: "item-frame" and "mob-spawning" for uses of item frame and mob-spawning?
@Muqsit

**Comment by Muqsit** [comment]
![xz](https://cloud.githubusercontent.com/assets/15074389/24009667/b44cca7e-0a86-11e7-8607-211cc22f35d8.PNG)
Use /rg flag set <region> fly-mode 3

**Comment by NycuRO** [comment]
@Muqsit And you can add flags: "item-frame" and "mob-spawning" for uses of item frame and mob-spawning?
