### ISSUE TITLE
Need to fix it to work with pocketmine latest build Please please please!(465)

### ISSUE THREAD

**Issue by jbreadtoasted** [Muqsit/WorldGuard#32]
Also if you could add it in so that when players are in a certain group rank wise like
<VIP+> Jbreadtoasty : 
So that i could allow a certain group like <VIP+> or they buy the permission to enter a location meaning that if they bought a rank or a permission like lets say wg.enter.regionname
that would allow them to go into the donor area or the vip area etc that would be epic thanks in advanced and i really hope you can get this updated asap so that i can use it on my upcomming better together server LETS BRING POCKETMINE COMMUNITY BACK!! @Muqsit @optimusprime338 Please!!!

**Comment by MasterOfTheRealm** [comment]
@jbreadtoasted updated version here -> https://github.com/MasterOfTheRealm/WorldGuard/tree/patch-1

**Comment by jbreadtoasted** [comment]
PocketMine-MP_1.7dev-473_d03fdd5f_API-3.0.0-ALPHA10.phar
--

**Comment by jbreadtoasted** [comment]
@MasterOfTheRealm Please help me to download this version idk how to..........
@jbreadtoasted updated version here -> https://github.com/MasterOfTheRealm/WorldGuard/tree/patch-1
I mean i  know how to download the worldguard v1 but when i do it still says dependencies for the lates version of pocketmine is not support and is still looking for these
How do i get the phar download that you fixed?
[Server] Server thread/ERROR Could not load plugin 'WorldGuard': Incompatible API version (plugin requires one of: 2.0.0, 3.0.0-ALPHA3, 3.0.0-ALPHA4)
