### ISSUE TITLE
Issue - Rewritten Branch

### ISSUE THREAD

**Issue by jrodr10** [Muqsit/WorldGuard#37]
Okay, i've run into an issues with the Rewritten branch.

1.Commands not working
Only commands that work are:
/wg pos1
/wg pos2
/wg create
/wg setflag
/wg delete

Command That Don't work(They send the help message) :
/wg info
/wg list

2. bows cannot be shot anywhere in the world when this plugin is in the plugin folder and enabled

**Comment by jbreadtoasted** [comment]
Are you using devtools to load in the plugin?

**Comment by Muqsit** [comment]
Rewrite branch is currently in-dev so expect bugs
