### ISSUE TITLE
how ?

### ISSUE THREAD

**Issue by LordJoshie** [Muqsit/WorldGuard#6]
how do you whitelist a player to edit the region, without allowing everyone else to edit the region?

**Comment by Muqsit** [comment]
Read the tutorial at https://github.com/Muqsit/WorldGuard/wiki/Tutorial

It's somewhere at the end of the page.

**Comment by LordJoshie** [comment]
my dude....trust me, I read it over and over and over...wanna jump on my
discord, I'll give u my TeamViewer controls and you can see what Im doing
and help ? lol and also, I had to edit the plugin to not take effects from
my players.-__-

**Comment by SinlesFlyer376** [comment]
There is nothing about whitelist in the tutorial

**Comment by LordJoshie** [comment]
well, there is.... but there isn't much about it, and it doesn't tell you
how to set flags for different whitelisted players....or if thats even
possible.

**Comment by Muqsit** [comment]
Just keep repeating the command with different players
/region flag set <region> whitelist player1
/region flag set <region> whitelist player2

If you would have read the wiki from top to not, you would've already figured it out.

**Comment by LordJoshie** [comment]
dude.... I don't think you understand... 

try it your goddamn self. 

having an argument on here if as fucking dumb as your whitelist feature on this plugin..


SO, BUD... ILL TYPE IN CAPS TO MAKE IT EXTRA FUCKIN CLEAR 

I HAVE TRIED, I KNOW HOW TO FUCKIN READ ENGLISH, I'M NEITHER A CHILD, NOR A TEEN... 

I DID WHAT YOUR STUPID WIKI HOW-TO HAD TO SAY, AND IT DIDNT DO WHAT WAS EXPECTED...


I MADE AN AREA, I WHITELISTED PEOPLE, NONE OF THEM COULD FUCKING DO ANYTHING. 

SO, IM ASKING THE DEVELOPER FOR HIS HELP, BUT HE'S TOO STUPID TO COMPREHEND THE PROBLEM I'M HAVING... 


I HAVE MADE AN AREA.... IM TRYING TO WHITELIST A PLAYER TO BE ABLE TO EDIT THE AREA, 
ON THE SAME AREA, IM TRYING TO MAKE IT SO A PLAYER CAN ENTER/EXIT, AND ANOTHER PLAYER CANNOT DO EITHER... 

HOW DO I SET DIFFERENT FLAGS FOR THE WHITELISTED PLAYERS... 

Not too fucking hard to answer... you either tell me how, or tell me your plugin was written pretty stupidly and that feature doesn't exist. 


Thanks for your time.

**Comment by LordJoshie** [comment]
^^ sorry for all that.... kinda.... 

just, you seem like an asshole when you aren't trying to understand my issue, and just keep saying your stupid shit over and over, which isn't solving anything.

**Comment by LordJoshie** [comment]
Also... idiot, this is your github wiki for this plugin... which doesn't say fuck all.


https://github.com/Muqsit/WorldGuard/wiki

**Comment by LordJoshie** [comment]
Also, I just went to look on https://poggit.pmmp.io/pi#paginate-1  where I found this plugin, and OH SHIT, IT'S NOT THERE ANYMORE. hmm.

**Comment by LordJoshie** [comment]
More Flags

notify-enter: Send a message when player enters a region. Usage: /region flags set <region-name> notify-enter Hello, you have entered this region.
notify-leave: Send a message when player leaves a region. Usage: /region flags set <region-name> notify-leave Hello, you have left this region.
allowed-enter: Allow/disallow players from entering a region. Set this flag to true or false.
allowed-leave: Allow/disallow players from leaving a region. Set this flag to true or false.
whitelist: Add player to whitelist. Usage: /region flags set <region-name> whitelist muqsitrayyanxo

^^ So.... with all this elaborate information about the whitelist feature of this plugin, where does it mention how you edit individual flags per whitelisted player ? ... hmm. I must have skipped over that part. 
cuz I don't see here how I'd change a flag of a whitelisted player...

**Comment by LordJoshie** [comment]
you'd think if you have flags for allow/leave, and have whitelisted players, you'd have seperate flags for whitelisted players...
