### ISSUE TITLE
Issue !

### ISSUE THREAD

**Issue by LordJoshie** [Muqsit/WorldGuard#7]
following these commands.... 

whitelist: Add player to whitelist. Usage: /region flags set <region-name> whitelist muqsitrayyanxo

produces this in the config...
    whitelist:
 muqsitrayyanxo: []

so... from that, how would I set the whitelisted players to be able to edit the area? I'm OP obviously, and I can't even edit the areas that I've whitelisted myself to. 

halp pl0x?

**Comment by Muqsit** [comment]
Send your region file

**Comment by LordJoshie** [comment]
Testerr:
  pos1:
  - 256
  - 66
  - 242
  pos2:
  - 250
  - 70
  - 235
  level: hub
  flags:
    editable: "false"
    pvp: "true"
    effects:
      16: "1"
    blocked-cmds: []
    allowed-cmds: []
    use: "false"
    item-drop: "true"
    explosion: "false"
    notify-enter: Safe Zone
    notify-leave: Danger Zone - dont go alone
    potions: "true"
    allowed-enter: "true"
    allowed-leave: "false"
    whitelist:
  Testdude1: []
  Testdude2: []
    game-mode: 0
    sleep: "true"
    send-chat: "true"
    receive-chat: "true"
    enderpearl: "true"
    fly-mode: 0

**Comment by Muqsit** [comment]
Do not modify whitelist directly from config

**Comment by LordJoshie** [comment]
okay, but how do i set flags for a player who is whitelisted... that's what
Im asking.

so that I can let a player enter/exit and area, and let one certain one
edit it.

**Comment by LordJoshie** [comment]
omg....



I did this.


and did not get the results desired.

I figured there might have been more...like...

region flags set Testerr whitelist jawshawa allow-enter true

region flags set Testerr whitelist jawshawa2 allow-enter false


region flags set Testerr whitelist jawshawa use


region flags set Testerr whitelist jawshtest allow-leave false



figured something like that would make sense....

**Comment by LordJoshie** [comment]
Good job helping me resolve the issue.... 
jk, since you didn't.
