### ISSUE TITLE
Flags?

### ISSUE THREAD

**Issue by SinlesFlyer** [Muqsit/WorldGuard#9]
A list of all the flags please I wanna be able to edit my spawn but I don't want other people to edit it...

**Comment by Muqsit** [comment]
https://github.com/Muqsit/WorldGuard/wiki/Tutorial

**Comment by SinlesFlyer** [comment]
Oh thanks

**Comment by SinlesFlyer** [comment]
Can you make sure on editable that ops can still build and nonops can't build?
Also, we can break things but we can't place things it says the message but everyone can break it....

**Comment by Muqsit** [comment]
How did you download this plugin?

**Comment by SinlesFlyer376** [comment]
I downloaded the .phar in it

**Comment by SinlesFlyer376** [comment]
https://github.com/Muqsit/WorldGuard/releases/download/v1.0/WorldGuard_v1.phar

**Comment by Muqsit** [comment]
Download the zip and compile it

**Comment by SinlesFlyer376** [comment]
Ok

**Comment by SinlesFlyer376** [comment]
Thank you!
